# config.toml
CAPTCHA_SERVICES_SUPPORTED = ["capsolver"]
DEFAULT_CAPTCHA_SERVICE = "capsolver"
SMS_SERVICES_SUPPORTED = ["getsmscode", "smspool"]
DEFAULT_SMS_SERVICE = "smspool"
SUPPORTED_BROWSERS = ['firefox', 'chrome']

[[SUPPORTED_SOLVERS_BY_EMAIL]]
email_service = "outlook"
solvers = ["capsolver"]

[[SUPPORTED_SOLVERS_BY_EMAIL]]
email_service = "yahoo"
solvers = ["capsolver"]
